/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Charity;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Manufactory;
import Business.Enterprise.School;
import Business.Enterprise.Storage;
import Business.Network;
import Business.Organization.CharityOrg;
import Business.Organization.Manufacture;
import Business.Organization.Organization;
import Business.Organization.SchoolOrg;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MS
 */
public class ManageEnterprisesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private JPanel container;
    private Network network;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private Organization org;

    public ManageEnterprisesJPanel(JPanel container, Network network) {

        initComponents();
        this.container = container;
        this.network = network;
//        this.customerDirectory = system.getCustomerDirectory();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        StorageTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        ManufactoryTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SchoolTable = new javax.swing.JTable();
        SchoolOrgBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        CharityTable = new javax.swing.JTable();
        CharityOrgBtn = new javax.swing.JButton();
        StorageOrgBtn = new javax.swing.JButton();
        SellOrgBtn = new javax.swing.JButton();
        ManuOrgBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 63, 86));

        StorageTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        StorageTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Address", "Phone Number"
            }
        ));
        jScrollPane3.setViewportView(StorageTable);

        ManufactoryTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ManufactoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Address", "Phone Number"
            }
        ));
        jScrollPane2.setViewportView(ManufactoryTable);

        backBtn.setBackground(new java.awt.Color(108, 122, 137));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/image/back.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        createBtn.setBackground(new java.awt.Color(52, 73, 94));
        createBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        createBtn.setForeground(new java.awt.Color(255, 255, 255));
        createBtn.setText("Create Enterprise");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        SchoolTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SchoolTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Address", "Phone Number"
            }
        ));
        jScrollPane1.setViewportView(SchoolTable);

        SchoolOrgBtn.setBackground(new java.awt.Color(44, 62, 80));
        SchoolOrgBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        SchoolOrgBtn.setForeground(new java.awt.Color(255, 255, 255));
        SchoolOrgBtn.setText("Manage School Organization");
        SchoolOrgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SchoolOrgBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Storage");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Manufactory");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Charity");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("School");

        CharityTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CharityTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Address", "Phone Number"
            }
        ));
        jScrollPane4.setViewportView(CharityTable);

        CharityOrgBtn.setBackground(new java.awt.Color(44, 62, 80));
        CharityOrgBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CharityOrgBtn.setForeground(new java.awt.Color(255, 255, 255));
        CharityOrgBtn.setText("Manage Charity Organization");
        CharityOrgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharityOrgBtnActionPerformed(evt);
            }
        });

        StorageOrgBtn.setBackground(new java.awt.Color(44, 62, 80));
        StorageOrgBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        StorageOrgBtn.setForeground(new java.awt.Color(255, 255, 255));
        StorageOrgBtn.setText("Manage Storage Organization");
        StorageOrgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StorageOrgBtnActionPerformed(evt);
            }
        });

        SellOrgBtn.setBackground(new java.awt.Color(44, 62, 80));
        SellOrgBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        SellOrgBtn.setForeground(new java.awt.Color(255, 255, 255));
        SellOrgBtn.setText("Manage Sell Organization");
        SellOrgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellOrgBtnActionPerformed(evt);
            }
        });

        ManuOrgBtn.setBackground(new java.awt.Color(44, 62, 80));
        ManuOrgBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ManuOrgBtn.setForeground(new java.awt.Color(255, 255, 255));
        ManuOrgBtn.setText("Manage Manufacture Organization");
        ManuOrgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManuOrgBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel3))
                            .addComponent(ManuOrgBtn)
                            .addComponent(SchoolOrgBtn)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CharityOrgBtn)
                                        .addComponent(StorageOrgBtn)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(118, 118, 118))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(285, 285, 285))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(279, 279, 279))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SellOrgBtn)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(518, 518, 518)
                        .addComponent(createBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CharityOrgBtn)
                    .addComponent(SchoolOrgBtn))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ManuOrgBtn)
                                .addGap(33, 33, 33)
                                .addComponent(SellOrgBtn))
                            .addComponent(StorageOrgBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        Component[] components = container.getComponents();
        SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel = (SystemAdminWorkAreaJPanel) container.getComponent(components.length - 1);
        systemAdminWorkAreaJPanel.populateTree();
        layout.previous(container);
    }//GEN-LAST:event_backBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        CreateEnterpriseJPanel createEnterpriseJPanel = new CreateEnterpriseJPanel(container, network);
        container.add("CreateEnterpriseJPanel", createEnterpriseJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_createBtnActionPerformed

    private void SchoolOrgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SchoolOrgBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = SchoolTable.getSelectedRow();
        if (selectedRow >= 0) {
            School school = (School) SchoolTable.getValueAt(selectedRow, 0);

            for (Organization og : school.getOrganizationDirectory().getOrganizationList()) {
                if (og.getType().equals(Organization.Type.School)) {
                    org = og;
                } else {
                    JOptionPane.showMessageDialog(null, "No Such Organization.", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            }
            ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(container, network, org);
            container.add("ManageOrganizationJPanel", manageOrganizationJPanel);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from table first.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_SchoolOrgBtnActionPerformed

    private void CharityOrgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharityOrgBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = CharityTable.getSelectedRow();
        if (selectedRow >= 0) {
            Charity charity = (Charity) CharityTable.getValueAt(selectedRow, 0);

            for (Organization og : charity.getOrganizationDirectory().getOrganizationList()) {
                if (og.getType().getValue().equals(Organization.Type.Charity.getValue())) {
                    org = og;
                } else {
                    JOptionPane.showMessageDialog(null, "No Such Organization.", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            }
            ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(container, network, org);
            container.add("ManageOrganizationJPanel", manageOrganizationJPanel);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from table first.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_CharityOrgBtnActionPerformed

    private void StorageOrgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StorageOrgBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = StorageTable.getSelectedRow();
        if (selectedRow >= 0) {
            Storage storage = (Storage) StorageTable.getValueAt(selectedRow, 0);

            for (Organization og : storage.getOrganizationDirectory().getOrganizationList()) {
                if (og.getType().equals(Organization.Type.Storage)) {
                    org = og;
                } else {
                    JOptionPane.showMessageDialog(null, "No Such Organization.", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            }
            ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(container, network, org);
            container.add("ManageOrganizationJPanel", manageOrganizationJPanel);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from table first.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_StorageOrgBtnActionPerformed

    private void SellOrgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellOrgBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = ManufactoryTable.getSelectedRow();
        if (selectedRow >= 0) {
            Manufactory manu = (Manufactory) ManufactoryTable.getValueAt(selectedRow, 0);

            for (Organization og : manu.getOrganizationDirectory().getOrganizationList()) {
                if (og.getType().equals(Organization.Type.Sell)) {
                    org = og;
                }
            }
            ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(container, network, org);
            container.add("ManageOrganizationJPanel", manageOrganizationJPanel);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from table first.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_SellOrgBtnActionPerformed

    private void ManuOrgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManuOrgBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = ManufactoryTable.getSelectedRow();
        if (selectedRow >= 0) {
            Manufactory manu = (Manufactory) ManufactoryTable.getValueAt(selectedRow, 0);

            for (Organization og : manu.getOrganizationDirectory().getOrganizationList()) {
                System.out.println(og.getType());
                if (og.getType().equals(Organization.Type.Manufacture)) {
                    org = og;
                }
            }
            ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(container, network, org);
            container.add("ManageOrganizationJPanel", manageOrganizationJPanel);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from table first.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ManuOrgBtnActionPerformed
    void populateTable() {
        DefaultTableModel dtm1 = (DefaultTableModel) SchoolTable.getModel();
        dtm1.setRowCount(0);
        DefaultTableModel dtm2 = (DefaultTableModel) CharityTable.getModel();
        dtm2.setRowCount(0);
        DefaultTableModel dtm3 = (DefaultTableModel) ManufactoryTable.getModel();
        dtm3.setRowCount(0);
        DefaultTableModel dtm4 = (DefaultTableModel) StorageTable.getModel();
        dtm4.setRowCount(0);
        for (Enterprise ep : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (ep instanceof School) {
                Object[] row1 = new Object[3];
                row1[0] = ep;
                row1[1] = ep.getAddress();
                row1[2] = ep.getPhonenum();
                dtm1.addRow(row1);
            } else if (ep instanceof Charity) {
                Object[] row2 = new Object[3];
                row2[0] = ep;
                row2[1] = ep.getAddress();
                row2[2] = ep.getPhonenum();
                dtm2.addRow(row2);
            } else if (ep instanceof Manufactory) {
                Object[] row3 = new Object[3];
                row3[0] = ep;
                row3[1] = ep.getAddress();
                row3[2] = ep.getPhonenum();
                dtm3.addRow(row3);
            } else if (ep instanceof Storage) {
                Object[] row4 = new Object[3];
                row4[0] = ep;
                row4[1] = ep.getAddress();
                row4[2] = ep.getPhonenum();
                dtm4.addRow(row4);
            }
        }
        //dB4OUtil.storeSystem(network);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CharityOrgBtn;
    private javax.swing.JTable CharityTable;
    private javax.swing.JButton ManuOrgBtn;
    private javax.swing.JTable ManufactoryTable;
    private javax.swing.JButton SchoolOrgBtn;
    private javax.swing.JTable SchoolTable;
    private javax.swing.JButton SellOrgBtn;
    private javax.swing.JButton StorageOrgBtn;
    private javax.swing.JTable StorageTable;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
