/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.ConfigureASystem;

import Business.DB4OUtil.DB4OUtil;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Charity;
import Business.Enterprise.Manufactory;
import Business.Enterprise.School;
import Business.Enterprise.Storage;
import Business.Network;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author ms
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
//    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private Network network;
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem system, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.system = system;
        populateTree();
        createDefaultEnterprise();

    }

    public void populateTree() {
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblSelectedNode = new javax.swing.JLabel();
        ManageEnterprisesBtn = new javax.swing.JButton();
        ManageRequestsBtn = new javax.swing.JButton();
        ManageNetworksBtn = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        jSplitPane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(33, 63, 86));

        lblSelectedNode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSelectedNode.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectedNode.setText("Welcome! System Administrator!");

        ManageEnterprisesBtn.setBackground(new java.awt.Color(44, 62, 80));
        ManageEnterprisesBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ManageEnterprisesBtn.setForeground(new java.awt.Color(255, 255, 255));
        ManageEnterprisesBtn.setText("Manage Enterprises");
        ManageEnterprisesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEnterprisesBtnActionPerformed(evt);
            }
        });

        ManageRequestsBtn.setBackground(new java.awt.Color(44, 62, 80));
        ManageRequestsBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ManageRequestsBtn.setForeground(new java.awt.Color(255, 255, 255));
        ManageRequestsBtn.setText("Manage Requests");
        ManageRequestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageRequestsBtnActionPerformed(evt);
            }
        });

        ManageNetworksBtn.setBackground(new java.awt.Color(44, 62, 80));
        ManageNetworksBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ManageNetworksBtn.setForeground(new java.awt.Color(255, 255, 255));
        ManageNetworksBtn.setText("Manage Networks");
        ManageNetworksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageNetworksBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ManageRequestsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(ManageNetworksBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(ManageEnterprisesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(360, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(lblSelectedNode)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblSelectedNode)
                .addGap(35, 35, 35)
                .addComponent(ManageEnterprisesBtn)
                .addGap(44, 44, 44)
                .addComponent(ManageRequestsBtn)
                .addGap(47, 47, 47)
                .addComponent(ManageNetworksBtn)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jSplitPane.setRightComponent(jPanel2);

        add(jSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void ManageEnterprisesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEnterprisesBtnActionPerformed
        ManageEnterprisesJPanel manageEnterprisesJPanel = new ManageEnterprisesJPanel(userProcessContainer, network);
        userProcessContainer.add("manageEnterprisesJPanel", manageEnterprisesJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageEnterprisesBtnActionPerformed

    private void ManageRequestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageRequestsBtnActionPerformed
        // TODO add your handling code here:
        ManageRequestJPanel manageRequestJPanel = new ManageRequestJPanel(userProcessContainer, network);
        userProcessContainer.add("manageRequestJPanel", manageRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageRequestsBtnActionPerformed

    private void ManageNetworksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageNetworksBtnActionPerformed
        // TODO add your handling code here:
        ManageNetworkJPanel manageNetworkJPanel = new ManageNetworkJPanel(userProcessContainer, system);
        userProcessContainer.add("manageNetworkJPanel", manageNetworkJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageNetworksBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageEnterprisesBtn;
    private javax.swing.JButton ManageNetworksBtn;
    private javax.swing.JButton ManageRequestsBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JLabel lblSelectedNode;
    // End of variables declaration//GEN-END:variables

    private void createDefaultEnterprise() {
                
                 //To change body of generated methods, choose Tools | Templates.
    }
}
