/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManufactureRole;

import Business.DB4OUtil.DB4OUtil;
import Business.Network;
import Business.Resourse.Resource;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.ChariryManagerRole.ViewCharityRequestJPanel;

/**
 *
 * @author MS
 */
public class ManufactureWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManufactureWorkAreaJPanel
     */private JPanel container;
//    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private Network network;
    private UserAccount account;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public ManufactureWorkAreaJPanel(JPanel userProcessContainer,UserAccount account, Network network) {
        initComponents();
        this.container = userProcessContainer;
        this.network = network;
        this.account = account;
        populateManufactureTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ManufactureWorkTable = new javax.swing.JTable();
        cancelbtn = new javax.swing.JButton();
        FinishDateTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ManufactureHistoryTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        submitbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ViewHistoryBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();
        AcceptBtn = new javax.swing.JButton();
        finishBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 63, 86));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Form:yyyy-MM-dd");

        ManufactureWorkTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ManufactureWorkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Request ID", "Amount", "Status"
            }
        ));
        jScrollPane1.setViewportView(ManufactureWorkTable);

        cancelbtn.setBackground(new java.awt.Color(44, 62, 80));
        cancelbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelbtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelbtn.setText("cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        FinishDateTxt.setBackground(new java.awt.Color(108, 122, 137));
        FinishDateTxt.setForeground(new java.awt.Color(255, 255, 255));

        ManufactureHistoryTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ManufactureHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Request ID", "Amount", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ManufactureHistoryTable);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Finished Date");

        submitbtn.setBackground(new java.awt.Color(44, 62, 80));
        submitbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitbtn.setForeground(new java.awt.Color(255, 255, 255));
        submitbtn.setText("submit");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("History");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Processing");

        ViewHistoryBtn.setBackground(new java.awt.Color(44, 62, 80));
        ViewHistoryBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewHistoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewHistoryBtn.setText("View");
        ViewHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewHistoryBtnActionPerformed(evt);
            }
        });

        ViewBtn.setBackground(new java.awt.Color(44, 62, 80));
        ViewBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewBtn.setText("View");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });

        AcceptBtn.setBackground(new java.awt.Color(44, 62, 80));
        AcceptBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AcceptBtn.setForeground(new java.awt.Color(255, 255, 255));
        AcceptBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/image/tongyi.png"))); // NOI18N
        AcceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptBtnActionPerformed(evt);
            }
        });

        finishBtn.setBackground(new java.awt.Color(44, 62, 80));
        finishBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        finishBtn.setForeground(new java.awt.Color(255, 255, 255));
        finishBtn.setText("Finish Producing");
        finishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(finishBtn)
                            .addComponent(jLabel4))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FinishDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(submitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewBtn)
                            .addComponent(AcceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ViewHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ViewBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AcceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3))
                    .addComponent(finishBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FinishDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cancelbtn)
                        .addComponent(submitbtn)))
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(ViewHistoryBtn)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        FinishDateTxt.setText("");
        FinishDateTxt.setEnabled(false);
        submitbtn.setEnabled(false);
        cancelbtn.setEnabled(false);
        finishBtn.setEnabled(true);
        populateManufactureTable();
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        int selectedRow = ManufactureWorkTable.getSelectedRow();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        if (selectedRow >= 0) {
            WorkRequest request = (WorkRequest) ManufactureWorkTable.getValueAt(selectedRow, 0);
            request.setStatus("Produced");

        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        FinishDateTxt.setText("");
        FinishDateTxt.setEnabled(false);
        submitbtn.setEnabled(false);
        cancelbtn.setEnabled(false);
        finishBtn.setEnabled(true);
    }//GEN-LAST:event_submitbtnActionPerformed

    private void ViewHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewHistoryBtnActionPerformed
        int selectedRow = ManufactureHistoryTable.getSelectedRow();
        if (selectedRow >= 0) {
            WorkRequest request = (WorkRequest) ManufactureHistoryTable.getValueAt(selectedRow, 0);
            ViewManuRequestJPanel viewManuRequestJPanel = new ViewManuRequestJPanel(request, container, account, network);
            container.add("ViewManuRequestJPanel", viewManuRequestJPanel);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ViewHistoryBtnActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        int selectedRow = ManufactureWorkTable.getSelectedRow();
        if (selectedRow >= 0) {
            WorkRequest request = (WorkRequest) ManufactureWorkTable.getValueAt(selectedRow, 0);
            ViewManuRequestJPanel viewManuRequestJPanel = new ViewManuRequestJPanel(request, container, account, network);
            container.add("ViewManuRequestJPanel", viewManuRequestJPanel);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ViewBtnActionPerformed

    private void AcceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptBtnActionPerformed
        int selectedRow = ManufactureWorkTable.getSelectedRow();
        if (selectedRow >= 0) {
            WorkRequest request = (WorkRequest) ManufactureWorkTable.getValueAt(selectedRow, 0);
            request.setStatus("Producing");
            request.setManufacture(account);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        populateManufactureTable();
    }//GEN-LAST:event_AcceptBtnActionPerformed

    private void finishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishBtnActionPerformed
        int selectedRow = ManufactureWorkTable.getSelectedRow();
        if (selectedRow >= 0) {
            FinishDateTxt.setEnabled(true);
            submitbtn.setEnabled(true);
            cancelbtn.setEnabled(true);
            finishBtn.setEnabled(false);}else {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first!", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_finishBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptBtn;
    private javax.swing.JTextField FinishDateTxt;
    private javax.swing.JTable ManufactureHistoryTable;
    private javax.swing.JTable ManufactureWorkTable;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JButton ViewHistoryBtn;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JButton finishBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton submitbtn;
    // End of variables declaration//GEN-END:variables

    

    public void populateManufactureTable() {
        DefaultTableModel dtm1 = (DefaultTableModel) ManufactureWorkTable.getModel();
        dtm1.setRowCount(0);
        for (WorkRequest req : network.getPool().getWorkRequestList()) {if(req.getManufactoryTodo()==null){}
        else if(req.getManufactoryTodo().getName().equals(account.getEmployee().getOrganization().getEnterprise().getName()))
            {if(req.getStatus().equals("Approved")||req.getStatus().equals("Producing")){
            Object[] row1 = new Object[3];
            row1[0] = req;
            row1[1] = req.getAmount();
            row1[2] = req.getStatus();
            dtm1.addRow(row1);}
        }}
        
        DefaultTableModel dtm2 = (DefaultTableModel) ManufactureHistoryTable.getModel();
        dtm2.setRowCount(0);
        for (WorkRequest req : network.getPool().getWorkRequestList()) {
            if(req.getManufacture()!=null){if(req.getManufacture().getEmployee().getOrganization().equals(account.getEmployee().getOrganization())){
            Object[] row2 = new Object[3];
            row2[0] = req;
            row2[1] = req.getAmount();
            row2[2] = req.getStatus();
            dtm2.addRow(row2);}}
        }
        FinishDateTxt.setEnabled(false);
        submitbtn.setEnabled(false);
        cancelbtn.setEnabled(false);
        finishBtn.setEnabled(true);
    }
}
