/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SellRole;

import Business.DB4OUtil.DB4OUtil;
import Business.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.ChariryManagerRole.ViewCharityRequestJPanel;

/**
 *
 * @author MS
 */
public class SellWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SellWorkAreaJPanel
     */private JPanel container;
//    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private Network network;
    private UserAccount account;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public SellWorkAreaJPanel(JPanel userProcessContainer,UserAccount account, Network network) {
        initComponents();
        this.container = userProcessContainer;
        this.network = network;
        this.account = account;
        populateSellTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        SellWorkTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        SellHistoryTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ViewBtn = new javax.swing.JButton();
        ViewHistoryBtn = new javax.swing.JButton();
        SoldBtn = new javax.swing.JButton();
        acceptBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 63, 86));

        SellWorkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Request ID", "Amount", "Status"
            }
        ));
        jScrollPane1.setViewportView(SellWorkTable);

        SellHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Request ID", "Amount", "Status"
            }
        ));
        jScrollPane2.setViewportView(SellHistoryTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Processing");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("History");

        ViewBtn.setBackground(new java.awt.Color(44, 62, 80));
        ViewBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ViewBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewBtn.setText("View");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });

        ViewHistoryBtn.setBackground(new java.awt.Color(44, 62, 80));
        ViewHistoryBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ViewHistoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewHistoryBtn.setText("View");
        ViewHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewHistoryBtnActionPerformed(evt);
            }
        });

        SoldBtn.setBackground(new java.awt.Color(44, 62, 80));
        SoldBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        SoldBtn.setForeground(new java.awt.Color(255, 255, 255));
        SoldBtn.setText("Sold");
        SoldBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoldBtnActionPerformed(evt);
            }
        });

        acceptBtn.setBackground(new java.awt.Color(44, 62, 80));
        acceptBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        acceptBtn.setForeground(new java.awt.Color(255, 255, 255));
        acceptBtn.setText("Accept");
        acceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(acceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SoldBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(ViewBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(ViewHistoryBtn)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acceptBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SoldBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(ViewBtn)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewHistoryBtn)
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewHistoryBtnActionPerformed
        int selectedRow = SellHistoryTable.getSelectedRow();
        if (selectedRow >= 0) {
            WorkRequest request = (WorkRequest) SellHistoryTable.getValueAt(selectedRow, 0);
            ViewCharityRequestJPanel viewCharityRequestJPanel = new ViewCharityRequestJPanel(request, container, account, network);
            container.add("ViewCharityRequestJPanel", viewCharityRequestJPanel);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ViewHistoryBtnActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        int selectedRow = SellWorkTable.getSelectedRow();
        if (selectedRow >= 0) {
            WorkRequest request = (WorkRequest) SellWorkTable.getValueAt(selectedRow, 0);
            ViewSellRequestJPanel viewSellRequestJPanel = new ViewSellRequestJPanel(request, container, account, network);
            container.add("ViewSellRequestJPanel", viewSellRequestJPanel);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ViewBtnActionPerformed

    private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBtnActionPerformed
        int selectedRow = SellWorkTable.getSelectedRow();
        if (selectedRow >= 0) {
            WorkRequest request = (WorkRequest) SellWorkTable.getValueAt(selectedRow, 0);
            request.setStatus("Selling");
            request.setSell(account);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        populateSellTable();
    }//GEN-LAST:event_acceptBtnActionPerformed

    private void SoldBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoldBtnActionPerformed
        int selectedRow = SellWorkTable.getSelectedRow();
        if (selectedRow >= 0) {
            WorkRequest request = (WorkRequest) SellWorkTable.getValueAt(selectedRow, 0);
            request.setStatus("Sold");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        populateSellTable();
    }//GEN-LAST:event_SoldBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable SellHistoryTable;
    private javax.swing.JTable SellWorkTable;
    private javax.swing.JButton SoldBtn;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JButton ViewHistoryBtn;
    private javax.swing.JButton acceptBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    void populateSellTable() {
       DefaultTableModel dtm1 = (DefaultTableModel) SellWorkTable.getModel();
        dtm1.setRowCount(0);
        for (WorkRequest req : network.getPool().getWorkRequestList()) {if(req.getManufactoryTodo()==null){}
        else if(req.getManufactoryTodo().getName().equals(account.getEmployee().getOrganization().getEnterprise().getName()))
            {if(req.getStatus().equals("Produced")||req.getStatus().equals("Selling")){
            Object[] row1 = new Object[3];
            row1[0] = req;
            row1[1] = req.getAmount();
            row1[2] = req.getStatus();
            dtm1.addRow(row1);}}
        }
        
        DefaultTableModel dtm2 = (DefaultTableModel) SellHistoryTable.getModel();
        dtm2.setRowCount(0);
        for (WorkRequest req : network.getPool().getWorkRequestList()) {
            if(req.getSell()!=null){if(req.getSell().getEmployee().getOrganization().equals(account.getEmployee().getOrganization())){
            Object[] row2 = new Object[3];
            row2[0] = req;
            row2[1] = req.getAmount();
            row2[2] = req.getStatus();
            dtm2.addRow(row2);}}
        }
    }
}
