/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SellRole;

import Business.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author MS
 */
public class ViewSellRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewRequestJPanel
     */
    private JPanel container;
    private Network network;
    private UserAccount account;
    private WorkRequest request;
    public ViewSellRequestJPanel(WorkRequest request,JPanel userProcessContainer,UserAccount account, Network network) {
        initComponents();
        this.network = network;
        this.container = userProcessContainer;
        this.account = account;
        this.request = request;
        SellReqeustDetailsPopulate(request);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        STxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FDTxt = new javax.swing.JTextField();
        SchoolTxt = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        IDTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ATxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CharityTxt = new javax.swing.JTextField();
        RDTxt = new javax.swing.JTextField();
        StorageTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ManufactureTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        employeeTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(33, 63, 86));

        STxt.setBackground(new java.awt.Color(108, 122, 137));
        STxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        STxt.setForeground(new java.awt.Color(240, 240, 240));
        STxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STxtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Status");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Storage");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("School");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Request Details");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Finish Date(If finished)");

        FDTxt.setBackground(new java.awt.Color(108, 122, 137));
        FDTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FDTxt.setForeground(new java.awt.Color(240, 240, 240));

        SchoolTxt.setBackground(new java.awt.Color(108, 122, 137));
        SchoolTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SchoolTxt.setForeground(new java.awt.Color(240, 240, 240));

        backBtn.setBackground(new java.awt.Color(108, 122, 137));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/image/back.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        IDTxt.setBackground(new java.awt.Color(108, 122, 137));
        IDTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        IDTxt.setForeground(new java.awt.Color(240, 240, 240));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("RequestID");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Charity");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Request Date");

        ATxt.setBackground(new java.awt.Color(108, 122, 137));
        ATxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ATxt.setForeground(new java.awt.Color(240, 240, 240));
        ATxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Amount");

        CharityTxt.setBackground(new java.awt.Color(108, 122, 137));
        CharityTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CharityTxt.setForeground(new java.awt.Color(240, 240, 240));

        RDTxt.setBackground(new java.awt.Color(108, 122, 137));
        RDTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RDTxt.setForeground(new java.awt.Color(240, 240, 240));
        RDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDTxtActionPerformed(evt);
            }
        });

        StorageTxt.setBackground(new java.awt.Color(108, 122, 137));
        StorageTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        StorageTxt.setForeground(new java.awt.Color(240, 240, 240));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Manufacture Account");

        ManufactureTxt.setBackground(new java.awt.Color(108, 122, 137));
        ManufactureTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ManufactureTxt.setForeground(new java.awt.Color(240, 240, 240));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Employee");

        employeeTxt.setBackground(new java.awt.Color(108, 122, 137));
        employeeTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        employeeTxt.setForeground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel9)
                        .addComponent(jLabel11)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel8)))
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FDTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(SchoolTxt)
                    .addComponent(CharityTxt)
                    .addComponent(STxt)
                    .addComponent(StorageTxt)
                    .addComponent(ManufactureTxt)
                    .addComponent(employeeTxt)
                    .addComponent(ATxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IDTxt)
                    .addComponent(RDTxt))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(43, 43, 43)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ATxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(STxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SchoolTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CharityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StorageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ManufactureTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(employeeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        Component[] components = container.getComponents();
        SellWorkAreaJPanel sellWorkAreaJPanel = (SellWorkAreaJPanel) container.getComponent(components.length - 1);
        sellWorkAreaJPanel.populateSellTable();
        layout.previous(container);
    }//GEN-LAST:event_backBtnActionPerformed

    private void ATxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ATxtActionPerformed

    private void RDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RDTxtActionPerformed

    private void STxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_STxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ATxt;
    private javax.swing.JTextField CharityTxt;
    private javax.swing.JTextField FDTxt;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JTextField ManufactureTxt;
    private javax.swing.JTextField RDTxt;
    private javax.swing.JTextField STxt;
    private javax.swing.JTextField SchoolTxt;
    private javax.swing.JTextField StorageTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField employeeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private void SellReqeustDetailsPopulate(WorkRequest request) {
        IDTxt.setText(String.valueOf(request.getReqID()));
        ATxt.setText(String.valueOf(request.getAmount()));
        RDTxt.setText(String.valueOf(request.getRequestDate()));
        STxt.setText(request.getStatus());
        if(request.getResolveDate()!=null){
        FDTxt.setText(String.valueOf(request.getResolveDate()));}else{FDTxt.setText("");}
        
        if(request.getCharity()!=null){
        CharityTxt.setText(request.getCharity().getEmployee().getOrganization().getEnterprise().toString());}else{CharityTxt.setText("");}
        
        if(request.getManufacture()!=null){
        ManufactureTxt.setText(request.getManufacture().getEmployee().toString());}else{ManufactureTxt.setText("");}
        
        if(request.getStorage()!=null){
        StorageTxt.setText(request.getStorage().getEmployee().getOrganization().getEnterprise().toString());}else{StorageTxt.setText("");}
        
        if(request.getSchool()!=null){
        SchoolTxt.setText(request.getSchool().getEmployee().getOrganization().getEnterprise().toString());}else{SchoolTxt.setText("");}
       
            if(request.getSell()!=null){
        employeeTxt.setText(request.getSell().getEmployee().getName());
        }
        IDTxt.setEnabled(false);
        ATxt.setEnabled(false);
        RDTxt.setEnabled(false);
        STxt.setEnabled(false);
        FDTxt.setEnabled(false);
        CharityTxt.setEnabled(false);
        ManufactureTxt.setEnabled(false);
        StorageTxt.setEnabled(false);
        SchoolTxt.setEnabled(false);
        employeeTxt.setEnabled(false);
    }
}
