/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.Customer.Customer;
import Business.Customer.Ticket;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;
/**
 *
 * @author MS
 */
public class ViewCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form View
     */
    private JPanel travelAgencyCL;
    private Customer customer;
    public ViewCustomerJPanel(JPanel travelAgencyCL, Customer customer) {
        initComponents();
        this.travelAgencyCL = travelAgencyCL;
        this.customer = customer;
        populate();
    }
    private void populate(){
         DefaultTableModel dtm = (DefaultTableModel) tblViewCustomer.getModel();
         dtm.setRowCount(0);
        
            for(Ticket t : customer.getTicketList()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = t; 
            Date date = t.getFlight().getDate();  
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
            String strDate = dateFormat.format(date);
            row[1] = strDate;
            row[2] = t.getFlight().getTime();
            row[3] = t.getFlight().getDeparture();
            row[4] = t.getFlight().getDestination();
            row[5] = t.getSeat();
            dtm.addRow(row);    
           
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDeleteFlight = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewCustomer = new javax.swing.JTable();

        btnDeleteFlight.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnDeleteFlight.setText("Delete");
        btnDeleteFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFlightActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel1.setText("View Customer Flight");

        btnBack.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblViewCustomer.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        tblViewCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Flight", "Departure Time", "Arrival Time", "Time Slot", "From", "To", "Seat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewCustomer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                    .addComponent(btnDeleteFlight))
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnBack)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnDeleteFlight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFlightActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblViewCustomer.getSelectedRow();
        if(selectedRow >=0){
            int dialogResult = JOptionPane.showConfirmDialog(null,"Would your like to delete the flight?","Warning",JOptionPane.WARNING_MESSAGE);
            if(dialogResult == JOptionPane.YES_NO_OPTION){
                Ticket t = (Ticket) tblViewCustomer.getValueAt(selectedRow,0);
                customer.deleteTicket(t);
                populate();
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Please select a row.","Warning",JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnDeleteFlightActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        travelAgencyCL.remove(this);
        CardLayout layout = (CardLayout) travelAgencyCL.getLayout();
        layout.previous(travelAgencyCL);

    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteFlight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblViewCustomer;
    // End of variables declaration//GEN-END:variables
}
