/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.AirlinerDirectory;
import Business.CustomerDirectory;
import Business.FlightSchedule;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author dell
 */
public class CustomerPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookedListPanel
     */
    private JPanel travelAgencyCL; 
    private FlightSchedule fs;
    private AirlinerDirectory ad;
    private CustomerDirectory cd;
    public CustomerPanel(JPanel travelAgencyCL, FlightSchedule fs, AirlinerDirectory ad, CustomerDirectory cd) {
        initComponents();
        this.travelAgencyCL = travelAgencyCL;
        this.fs = fs;
        this.ad = ad;
        this.cd = cd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reservedListBTN = new javax.swing.JButton();
        searchBTN = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(681, 483));

        reservedListBTN.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        reservedListBTN.setText("Reserved List");
        reservedListBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservedListBTNActionPerformed(evt);
            }
        });

        searchBTN.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        searchBTN.setText("Search for Flight");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(reservedListBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(reservedListBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        CustomerSearchPanel CSP = new CustomerSearchPanel(travelAgencyCL, fs, ad, cd);
        travelAgencyCL.add("CustomerSearchPanel", CSP);
        CardLayout cl = (CardLayout)travelAgencyCL.getLayout();
        cl.next(travelAgencyCL);
    }//GEN-LAST:event_searchBTNActionPerformed

    private void reservedListBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservedListBTNActionPerformed
        ReservedListPanel RLP = new ReservedListPanel(travelAgencyCL, fs, cd);
        travelAgencyCL.add("ReservedListPanel", RLP);
        CardLayout cl = (CardLayout)travelAgencyCL.getLayout();
        cl.next(travelAgencyCL);
    }//GEN-LAST:event_reservedListBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton reservedListBTN;
    private javax.swing.JButton searchBTN;
    // End of variables declaration//GEN-END:variables
}
