/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.*;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;

/**
 *
 * @author dell
 */
public class ManageCustomerPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomerPanel
     */
    private JPanel travelAgencyCL;
    private FlightSchedule fs;
    private CustomerDirectory cd;
    private AirlinerDirectory ad;
    private String[] info;

    public ManageCustomerPanel(JPanel travelAgencyCL, FlightSchedule fs, CustomerDirectory cd, AirlinerDirectory ad, String[] info) {
        initComponents();
        this.travelAgencyCL = travelAgencyCL;
        this.fs = fs;
        this.cd = cd;
        this.ad = ad;
        this.info = info;
        populate();
    }

    public void populate() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        DefaultTableModel dtm = (DefaultTableModel) flightScheduleTBL.getModel();
        dtm.setRowCount(0);
        FlightSchedule resultFS = filterSchedule();

        if (resultFS != null) {
            for (Flights f : resultFS.getFlightDir()) {
                Object[] row = new Object[dtm.getColumnCount()];
                row[0] = f.getAirplane().getAirlinerName();
                row[1] = f;
                row[2] = f.getDeparture();
                row[3] = f.getDestination();
                row[4] = sdf.format(f.getDate());
                row[5] = f.getTime();
                dtm.addRow(row);
            }
        }
    }

    private FlightSchedule filterSchedule() {
        FlightSchedule resultFS = fs;
        String departure = info[0];
        String destination = info[1];
        String date = info[2];
        String time = info[3];
        String airliner = info[4];

        if (!departure.equals("default")) {
            try {
                resultFS = resultFS.filterDeparture(departure);
            } catch (Exception e) {
            }
        }
        if (!destination.equals("default")) {
            try {
                resultFS = resultFS.filterDestination(destination);
            } catch (Exception e) {
            }
        }
        if (!date.equals("default")) {
            try {
                resultFS = resultFS.filterDate(date);
            } catch (Exception e) {
            }
        }
        if (!time.equals("default")) {
            try {
                resultFS = resultFS.filterTime(time);
            } catch (Exception e) {
            }
        }
        if (!airliner.equals("default")) {
            try {
                resultFS = resultFS.filterAirliner(airliner);
                System.out.println(resultFS.getFlightDir().get(0));
            } catch (Exception e) {
            }
        }
        return resultFS;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flightScheduleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightScheduleTBL = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(681, 483));

        flightScheduleLabel.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        flightScheduleLabel.setText("Customer Search Result");

        flightScheduleTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner Name", "Flight Number", "Depature", "Destnation", "Date", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(flightScheduleTBL);

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View >>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(flightScheduleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(flightScheduleLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout cl = (CardLayout) travelAgencyCL.getLayout();
        cl.previous(travelAgencyCL);
        travelAgencyCL.remove(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = flightScheduleTBL.getSelectedRow();
        if (selectedRow >= 0) {
            Flights flight = (Flights) flightScheduleTBL.getValueAt(selectedRow, 1);
            CustomerViewPanel CVP = new CustomerViewPanel(travelAgencyCL, fs, cd, flight);
            travelAgencyCL.add("CustomerViewPanel", CVP);
            CardLayout cl = (CardLayout) travelAgencyCL.getLayout();
            cl.next(travelAgencyCL);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a Row!!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel flightScheduleLabel;
    private javax.swing.JTable flightScheduleTBL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
