/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SchoolRole;

import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.SystemAdminWorkArea.CreateEnterpriseJPanel;

/**
 *
 * @author MS
 */
public class SchoolWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SchoolWorkAreaJPanel
     */
    private JPanel container;
//    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private Network network;
    private UserAccount account;

    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    public SchoolWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Network network) {
        initComponents();
        this.container = userProcessContainer;
        this.network = network;
        this.account = account;
        populateSchoolTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        SchoolWorkTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        CreateBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();
        ReceiveBtn = new javax.swing.JButton();
        FinishDateTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        submitbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cancelbtn = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setBackground(new java.awt.Color(33, 63, 86));

        jScrollPane1.setForeground(new java.awt.Color(240, 240, 240));

        SchoolWorkTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SchoolWorkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Request ID", "Amount", "Status"
            }
        ));
        jScrollPane1.setViewportView(SchoolWorkTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Requests");

        CreateBtn.setBackground(new java.awt.Color(44, 62, 80));
        CreateBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateBtn.setForeground(new java.awt.Color(255, 255, 255));
        CreateBtn.setText("Create a New Request");
        CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBtnActionPerformed(evt);
            }
        });

        ViewBtn.setBackground(new java.awt.Color(44, 62, 80));
        ViewBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ViewBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewBtn.setText("View Details");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });

        ReceiveBtn.setBackground(new java.awt.Color(44, 62, 80));
        ReceiveBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ReceiveBtn.setForeground(new java.awt.Color(255, 255, 255));
        ReceiveBtn.setText("Received");
        ReceiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceiveBtnActionPerformed(evt);
            }
        });

        FinishDateTxt.setBackground(new java.awt.Color(108, 122, 137));
        FinishDateTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FinishDateTxt.setForeground(new java.awt.Color(240, 240, 240));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Finished Date");

        submitbtn.setBackground(new java.awt.Color(44, 62, 80));
        submitbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        submitbtn.setForeground(new java.awt.Color(255, 255, 255));
        submitbtn.setText("submit");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Form:yyyy-MM-dd");

        cancelbtn.setBackground(new java.awt.Color(44, 62, 80));
        cancelbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelbtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelbtn.setText("cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ReceiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(FinishDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cancelbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(submitbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(CreateBtn)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ViewBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitbtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ReceiveBtn)
                            .addComponent(FinishDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(cancelbtn)))
                .addGap(41, 41, 41)
                .addComponent(CreateBtn)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBtnActionPerformed
        // TODO add your handling code here:
        CreateSchoolRequestJPanel createSchoolRequestJPanel = new CreateSchoolRequestJPanel(container, account, network);
        container.add("CreateSchoolRequestJPanel", createSchoolRequestJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_CreateBtnActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = SchoolWorkTable.getSelectedRow();
        if (selectedRow >= 0) {
            WorkRequest request = (WorkRequest) SchoolWorkTable.getValueAt(selectedRow, 0);
            ViewSchoolRequestJPanel viewSchoolRequestJPanel = new ViewSchoolRequestJPanel(request, container, account, network);
            container.add("ViewSchoolRequestJPanel", viewSchoolRequestJPanel);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ViewBtnActionPerformed

    private void ReceiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceiveBtnActionPerformed
        int selectedRow = SchoolWorkTable.getSelectedRow();
        if (selectedRow >= 0){
        FinishDateTxt.setEnabled(true);
        submitbtn.setEnabled(true);
        cancelbtn.setEnabled(true);
        ReceiveBtn.setEnabled(false);}else{JOptionPane.showMessageDialog(null, "Please select a row from the table first!", "Warning", JOptionPane.WARNING_MESSAGE);}
    }//GEN-LAST:event_ReceiveBtnActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        int selectedRow = SchoolWorkTable.getSelectedRow();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        if (selectedRow >= 0) {
            WorkRequest request = (WorkRequest) SchoolWorkTable.getValueAt(selectedRow, 0);
            request.setStatus("Finished");
            try {
                sdf.parse(FinishDateTxt.getText());
            } catch (Exception exc) {
                JOptionPane.showMessageDialog(this, "Please fill date in yyyy-MM-dd format into date field!!");
                return;
            }
            try {
                sdf.setLenient(false);
                sdf.parse(FinishDateTxt.getText());
            } catch (Exception exc) {
                JOptionPane.showMessageDialog(this, "Date is illegal!!!");
                return;
            }
            try {
                request.setResolveDate(sdf.parse(FinishDateTxt.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Fail!");
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        FinishDateTxt.setText("");
        FinishDateTxt.setEnabled(false);
        submitbtn.setEnabled(false);
        cancelbtn.setEnabled(false);
        ReceiveBtn.setEnabled(true);
        populateSchoolTable();
    }//GEN-LAST:event_submitbtnActionPerformed

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        FinishDateTxt.setText("");
        FinishDateTxt.setEnabled(false);
        submitbtn.setEnabled(false);
        cancelbtn.setEnabled(false);
        ReceiveBtn.setEnabled(true);
        populateSchoolTable();
    }//GEN-LAST:event_cancelbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateBtn;
    private javax.swing.JTextField FinishDateTxt;
    private javax.swing.JButton ReceiveBtn;
    private javax.swing.JTable SchoolWorkTable;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton submitbtn;
    // End of variables declaration//GEN-END:variables

    public void populateSchoolTable() {
        DefaultTableModel dtm1 = (DefaultTableModel) SchoolWorkTable.getModel();
        dtm1.setRowCount(0);
        for (WorkRequest req : network.getPool().getWorkRequestList()) {
            if(req.getSchool().getEmployee().getOrganization().equals(account.getEmployee().getOrganization())){
            Object[] row = new Object[3];
            row[0] = req;
            row[1] = req.getAmount();
            row[2] = req.getStatus();
            dtm1.addRow(row);}else{}
        }
        FinishDateTxt.setEnabled(false);
        submitbtn.setEnabled(false);
        cancelbtn.setEnabled(false);
    }
}
