/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SchoolRole;

import Business.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author MS
 */
public class ViewSchoolRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewSchoolRequestJPanel
     */
    private JPanel container;
    private Network network;
    private UserAccount account;
    private WorkRequest request;
    public ViewSchoolRequestJPanel(WorkRequest request,JPanel userProcessContainer,UserAccount account, Network network) {
        initComponents();
        this.network = network;
        this.container = userProcessContainer;
        this.account = account;
        this.request = request;
        SchoolReqeustDetailsPopulate(request);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        ATxt = new javax.swing.JTextField();
        RDTxt = new javax.swing.JTextField();
        STxt = new javax.swing.JTextField();
        FDTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CharityTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ManuTxt = new javax.swing.JTextField();
        StorageTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        employeeTxt = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setBackground(new java.awt.Color(33, 63, 86));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Request Details");

        backBtn.setBackground(new java.awt.Color(108, 122, 137));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/image/back.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RequestID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Amount");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Request Date");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Status");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Finish Date(If finished)");

        IDTxt.setBackground(new java.awt.Color(108, 122, 137));
        IDTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        IDTxt.setForeground(new java.awt.Color(255, 255, 255));

        ATxt.setBackground(new java.awt.Color(108, 122, 137));
        ATxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ATxt.setForeground(new java.awt.Color(255, 255, 255));
        ATxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATxtActionPerformed(evt);
            }
        });

        RDTxt.setBackground(new java.awt.Color(108, 122, 137));
        RDTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RDTxt.setForeground(new java.awt.Color(255, 255, 255));
        RDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDTxtActionPerformed(evt);
            }
        });

        STxt.setBackground(new java.awt.Color(108, 122, 137));
        STxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        STxt.setForeground(new java.awt.Color(255, 255, 255));

        FDTxt.setBackground(new java.awt.Color(108, 122, 137));
        FDTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FDTxt.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Charity");

        CharityTxt.setBackground(new java.awt.Color(108, 122, 137));
        CharityTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CharityTxt.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Manufactory");

        ManuTxt.setBackground(new java.awt.Color(108, 122, 137));
        ManuTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ManuTxt.setForeground(new java.awt.Color(255, 255, 255));

        StorageTxt.setBackground(new java.awt.Color(108, 122, 137));
        StorageTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        StorageTxt.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Storage");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Employee");

        employeeTxt.setBackground(new java.awt.Color(108, 122, 137));
        employeeTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        employeeTxt.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(148, 148, 148))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ATxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(IDTxt)
                            .addComponent(RDTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(STxt)
                            .addComponent(FDTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CharityTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(ManuTxt)
                            .addComponent(StorageTxt)
                            .addComponent(employeeTxt))))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(ATxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(RDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(STxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel8)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CharityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(ManuTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(StorageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(employeeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        Component[] components = container.getComponents();
        SchoolWorkAreaJPanel schoolWorkAreaJPanel = (SchoolWorkAreaJPanel) container.getComponent(components.length - 1);
        schoolWorkAreaJPanel.populateSchoolTable();
        layout.previous(container);
    }//GEN-LAST:event_backBtnActionPerformed

    private void ATxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ATxtActionPerformed

    private void RDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RDTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ATxt;
    private javax.swing.JTextField CharityTxt;
    private javax.swing.JTextField FDTxt;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JTextField ManuTxt;
    private javax.swing.JTextField RDTxt;
    private javax.swing.JTextField STxt;
    private javax.swing.JTextField StorageTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField employeeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    public void SchoolReqeustDetailsPopulate(WorkRequest request) {
        IDTxt.setText(String.valueOf(request.getReqID()));
        ATxt.setText(String.valueOf(request.getAmount()));
        RDTxt.setText(String.valueOf(request.getRequestDate()));
        STxt.setText(request.getStatus());
        if(request.getResolveDate()!=null){
        FDTxt.setText(String.valueOf(request.getResolveDate()));}else{FDTxt.setText("");}
        
        if(request.getCharity()!=null){
        CharityTxt.setText(request.getCharity().getEmployee().getOrganization().getEnterprise().toString());}else{CharityTxt.setText("");}
        
        if(request.getManufacture()!=null){
        ManuTxt.setText(request.getManufacture().getEmployee().getOrganization().getEnterprise().toString());}else{ManuTxt.setText("");}
        
        if(request.getStorage()!=null){
        StorageTxt.setText(request.getStorage().getEmployee().getOrganization().getEnterprise().toString());}else{StorageTxt.setText("");}
        
        if(request.getSchool()!=null){
        employeeTxt.setText(request.getSchool().getEmployee().getName());
        }
        IDTxt.setEnabled(false);
        ATxt.setEnabled(false);
        RDTxt.setEnabled(false);
        STxt.setEnabled(false);
        FDTxt.setEnabled(false);
        CharityTxt.setEnabled(false);
        ManuTxt.setEnabled(false);
        StorageTxt.setEnabled(false);
        employeeTxt.setEnabled(false);
        
        
        
                }
}
