/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Airliner.Airliner;
import Business.Schedule.FlightSchedule;
import Business.Customer.CustomerDirectory;
import Business.Airliner.AirlinerDirectory;
import Interface.Customer.Managecustomer;
import Interface.MasterFlightSchedule.FlightLoginPanel;
import Interface.TravelAgency.ManageTravelAgencyPanel;
import java.awt.CardLayout;
/**
 *
 * @author dell
 */
public class BasicFrame extends javax.swing.JFrame {

    /**
     * Creates new form BasicFrame
     */
    private AirlinerDirectory airlinerDic;
    private FlightSchedule fs;
    private CustomerDirectory cd;
    public BasicFrame() {
        initComponents();
        this.airlinerDic = new AirlinerDirectory();
        this.fs = new FlightSchedule();
        this.cd = new CustomerDirectory();
        this.airlinerDic = new AirlinerDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        ButtonPanel = new javax.swing.JPanel();
        travelAgencyBTN = new javax.swing.JButton();
        flightScheduleBTN = new javax.swing.JButton();
        customerBTN = new javax.swing.JButton();
        CardLayoutPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(180);

        ButtonPanel.setOpaque(false);
        ButtonPanel.setPreferredSize(new java.awt.Dimension(180, 483));

        travelAgencyBTN.setText("Airliners");
        travelAgencyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travelAgencyBTNActionPerformed(evt);
            }
        });

        flightScheduleBTN.setText("Flights");
        flightScheduleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightScheduleBTNActionPerformed(evt);
            }
        });

        customerBTN.setText("Customers");
        customerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(travelAgencyBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flightScheduleBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(travelAgencyBTN)
                .addGap(80, 80, 80)
                .addComponent(flightScheduleBTN)
                .addGap(80, 80, 80)
                .addComponent(customerBTN)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(ButtonPanel);

        CardLayoutPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(CardLayoutPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void travelAgencyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travelAgencyBTNActionPerformed
        ManageTravelAgencyPanel MTAP = new ManageTravelAgencyPanel(CardLayoutPanel, airlinerDic);
        CardLayoutPanel.add("ManageTravelAgencyPanel", MTAP);
        CardLayout cl = (CardLayout)CardLayoutPanel.getLayout();
        cl.next(CardLayoutPanel);
    }//GEN-LAST:event_travelAgencyBTNActionPerformed

    private void flightScheduleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightScheduleBTNActionPerformed
        FlightLoginPanel FLP = new FlightLoginPanel(CardLayoutPanel, fs, airlinerDic);
        CardLayoutPanel.add("FlightLoginPanel", FLP);
        CardLayout cl = (CardLayout)CardLayoutPanel.getLayout();
        cl.next(CardLayoutPanel);
    }//GEN-LAST:event_flightScheduleBTNActionPerformed

    private void customerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBTNActionPerformed
        Managecustomer CP = new Managecustomer(CardLayoutPanel,cd,fs,airlinerDic);
        CardLayoutPanel.add("CustomerSearchPanel", CP);
        CardLayout cl = (CardLayout)CardLayoutPanel.getLayout();
        cl.next(CardLayoutPanel);
    }//GEN-LAST:event_customerBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasicFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasicFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasicFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasicFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasicFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel CardLayoutPanel;
    private javax.swing.JButton customerBTN;
    private javax.swing.JButton flightScheduleBTN;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton travelAgencyBTN;
    // End of variables declaration//GEN-END:variables
}
