/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.TravelAgency;

import Business.Airliner.AirlinerDirectory;
import Business.Airliner.Airliner;
import Business.Airliner.Airplane;
import java.awt.CardLayout;
import javax.swing.JPanel;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class AirlinerViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form AirlinerViewPanel
     */
    private Airliner al;
    private JPanel travelAgencyCL;

    public AirlinerViewPanel(JPanel travelAgencyCL, Airliner al) {
        initComponents();
        this.travelAgencyCL = travelAgencyCL;
        this.al = al;
        nameTF.setText(al.getName());
        String airplaneNum = "";
        for (Airplane ap : al.getAirplanesDir()) {
            airplaneNum = airplaneNum + ap.getAirplaneNum() + ",";
        }
        airplaneNumTF.setText(airplaneNum.substring(0, airplaneNum.length() - 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        backBTN = new javax.swing.JButton();
        submitBTN = new javax.swing.JButton();
        updateBTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        airplaneNumTF = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(681, 483));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel1.setText("View Airliners");

        nameTF.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel2.setText("Name");

        backBTN.setText("<< Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        submitBTN.setText("Submit");
        submitBTN.setEnabled(false);
        submitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTNActionPerformed(evt);
            }
        });

        updateBTN.setText("Update");
        updateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTNActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel5.setText("Airplane Numbers");

        airplaneNumTF.setEditable(false);
        airplaneNumTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airplaneNumTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addComponent(updateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(submitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(airplaneNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addComponent(airplaneNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBTN)
                    .addComponent(backBTN)
                    .addComponent(submitBTN))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        travelAgencyCL.remove(this);
        CardLayout cl = (CardLayout) travelAgencyCL.getLayout();
        Component[] comps = travelAgencyCL.getComponents();
        for (Component comp : comps) {
            if (comp instanceof ManageTravelAgencyPanel) {
                ManageTravelAgencyPanel MTAP = (ManageTravelAgencyPanel) comp;
                MTAP.populate();
            }
        }
        cl.previous(travelAgencyCL);
    }//GEN-LAST:event_backBTNActionPerformed

    private void submitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTNActionPerformed
        if (nameTF.getText().isEmpty() || airplaneNumTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields!!");
            return;
        } else {
            
            String[] airplaneNum = null;
            airplaneNum = airplaneNumTF.getText().split(",");
            for (int i = 0; i < airplaneNum.length; i++) {
                for (int j = i + 1; j < airplaneNum.length; j++) {
                    if (airplaneNum[i].equals(airplaneNum[j])) {
                        JOptionPane.showMessageDialog(this, "Airplane number is illegal!");
                        return;
                    }
                }
            }
            al.deleteAirplane();
            for (String aN : airplaneNum) {
                Airplane ap = al.addAirplane();
                ap.setAirlinerName(nameTF.getText());
                ap.setAirplaneNum(aN);
            }
            al.setName(nameTF.getText());
           

            JOptionPane.showMessageDialog(this, "Airliner updated Successfully");

            nameTF.setEditable(false);

            airplaneNumTF.setEditable(false);
            submitBTN.setEnabled(false);
            updateBTN.setEnabled(true);
        }
    }//GEN-LAST:event_submitBTNActionPerformed

    private void updateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTNActionPerformed
        nameTF.setEditable(true);

        airplaneNumTF.setEditable(true);
        submitBTN.setEnabled(true);
        updateBTN.setEnabled(false);
    }//GEN-LAST:event_updateBTNActionPerformed

    private void airplaneNumTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airplaneNumTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airplaneNumTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airplaneNumTF;
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton submitBTN;
    private javax.swing.JButton updateBTN;
    // End of variables declaration//GEN-END:variables
}
